### ISSUE TITLE
How to Extend Colours?

### ISSUE THREAD

**Issue by aljawaid** [aljawaid/KBColours#1]
- How can we add a colour to the default colours model?
- Should we create a new database for new colours? or add in the app settings metadata?

**Comment by aljawaid** [comment]
@creecros Hello, any input on your side for the above questions?  If you could use the app model to create a random colour for me, I can then look into the code and make more colours.  I have no idea how to work with the model.

So far, the plugin displays the default colours in a settings page with the values and now also the dropdowns show the coloured boxes.

**Comment by creecros** [comment]
https://github.com/creecros/Group_assign/blob/master/Model/GroupColorExtension.php

**Comment by creecros** [comment]
There is also a hook, you can just add colors using the hook:

https://github.com/kanboard/kanboard/blob/7c0a239ec399124207b86fcd6b22ade38c5c7574/app/Model/ColorModel.php#L157

**Comment by aljawaid** [comment]
> There is also a hook, you can just add colors using the hook:
> 
> https://github.com/kanboard/kanboard/blob/7c0a239ec399124207b86fcd6b22ade38c5c7574/app/Model/ColorModel.php#L157

I saw this but how do I work with it? it's not the same as a template hook.

```
$this->hook->reference('model:color:get-list', $listing);
```

**Should I code?**
```
$this->hook->reference('model:color:get-list', config/new-colours);   // plugin template file
```
then the plugin template file contains text fields with manual colour values that it can add to the list

**Comment by creecros** [comment]
I've been playing with it for the hour and have yet to figure it out

**Comment by creecros** [comment]
I figured it out, I'll explain it once i get a moment to fully explain it.

**Comment by creecros** [comment]
It should be updated now so that you can easily add colors.

what you can do now is instead of hard coding the colors into the plugin, use metadata and allow people to add their own colors.

**Comment by creecros** [comment]
Im also proud to say, i did it with 0 overrides

**Comment by aljawaid** [comment]
> It should be updated now so that you can easily add colors.
woaaah thanks! let me study that...

> what you can do now is instead of hard coding the colors into the plugin, use metadata and allow people to add their own colors. (this might be tricky if you don't know what you are doing, because you going to need arrays and metadata columns do not save array data, only strings. You will need to convert array to string when saving and string to array when reading.)
will consider... i am doing this colours thing because of my tags plugin as i have x amount of tags with customcss colours which i am thinking i will add to the protected function you created and see how i can play with it (the white and maroon were tests, which might hold my customised list... will test)

**Comment by aljawaid** [comment]
@creecros Is this hook still needed after the latest commits?

https://github.com/aljawaid/KBColours/blob/691778c880216de4999a0bcf3013e2bb440d0fcd/Plugin.php#L31
