### ISSUE TITLE
Add Custom Colour Palette

### ISSUE THREAD

**Issue by aljawaid** [aljawaid/KBColours#3]

**Comment by creecros** [comment]
I actually started this last night, and then fell asleep when I hit a road block.

**Comment by creecros** [comment]
Got this working. I put a lot of work into this, but you made commits last night, ill do my best to combine, but do me a favour and wait until i get this merged to make anymore commits.

**Comment by creecros** [comment]
now i just need to build a remove function. it's christmas, so i dont gaurantee i can get this done today.

**Comment by creecros** [comment]
did the best i could to merge

**Comment by aljawaid** [comment]
> did the best i could to merge

hello, is it done? can I continue on my commits? (I'm just adding my custom colours to the protected function)
your new function will be excellent.... so there will be 16 defaults, xx custom (from my list) and then the user can add/remove his own color.  Excellent.... another things that should have been part of the core!

**Comment by creecros** [comment]
There is no more "protected" function. I also remove any hardcoded color definitions in your css, as that will become useless now that people can add remove colors.

**Comment by creecros** [comment]
and yes it is complete

**Comment by aljawaid** [comment]
> did the best i could to merge

just confused on what I can add back in or not... the protected function was going great and would have been beautiful side by side with add/remove

**Comment by creecros** [comment]
> > did the best i could to merge
> 
> just confused on what I can add back in or not... the protected function was going great and would have been beautiful side by side with add/remove

not sure why you think that, the protected "variable" is obsolete, hard coded colors. now everything is dynamic. If you want preinstalled colors, just add them into the metadata.

**Comment by aljawaid** [comment]
> > > did the best i could to merge
> > 
> > 
> > just confused on what I can add back in or not... the protected function was going great and would have been beautiful side by side with add/remove
> 
> not sure why you think that, the protected "variable" is obsolete, hard coded colors. now everything is dynamic. If you want preinstalled colors, just add them into the metadata.

yes I agree with you but I was leaning towards a hardcoded extra colour palette to add to the core 16 colours.. dynamic is great and needed but my extra colour palette was more suitable for 'tags' with coloured text also (see my example, white on maroon)

**Comment by aljawaid** [comment]
@creecros I'm thinking... (without testing your latest changes)...

- we have 16 core colours with no issues, hardcoded
- dynamic custom colors (as your latest commits) perfect
- predefined 'extra colours' (with text colour included)

> i think you are missing the point.
> 
> You want this plugin to come with extra colors, i.e. white and maroon. You think that because i removed the hardcoded colors, this is not possible. But this is very possible, and you can now do it by simply adding the color data into the metadata tables. Because everything is dynamic, you dont have to do a darn thing other than that, even the css is built "automatically" for you.

I know what you are saying, but the metadata table is just for me... not ANY user like YOU or ANYONE, just MY SETUP.

**Comment by creecros** [comment]
opps, I edited your comment instead of replying. sorry, fat thumbs on a cell phone

**Comment by aljawaid** [comment]
> not sure you understand still.
> 
> if you program the plugin to put color data into the metadata, then that metadata is for EVERYONE who installs the plugin.

oooooh right I see, that was my biggest worry... I'm going to pull your changes shortly and play with it.... it will make more sense then.... I will copy (unless its complicated) your edits to add a font-color to the metadata as the colours I have are focused for tags

**Comment by aljawaid** [comment]
> not sure you understand still.
> 
> if you program the plugin to put color data into the metadata, then that metadata is for EVERYONE who installs the plugin.
@creecros 
how can I pre-populate that data? I just pulled your changes... if I add custom colours, they are not for you (my git shows no changes to merge, no entries in database for metadata, no mentions in code of the colour i just added obviously)

So, to pre-populate, i think i will still need a hardcoded list like before in addition to letting the user add/remove his own

**Comment by creecros** [comment]
I will have to play with it tonight, i kind of dont have any more time today.

**Comment by aljawaid** [comment]
> I will have to play with it tonight, i kind of dont have any more time today.

kind of? you make it sound like youre on a different planet not a different timezone hahahaha

Do you understand what I mean now about pre-populated data?  thats why I think, in addition to what you have done, the hardcoded protected function needs to come back... so that on installing, users have a core list, an extra list, and a user-defined empty custom list.  the extra list would be the private deleted function with font-color included as i had already managed to get that done.

this way, no need for database and the invisible metadata will only exist for user generated colors, not the core nor the extra list

**Comment by aljawaid** [comment]
> I will have to play with it tonight, i kind of dont have any more time today.

if you agree with what i am saying and understand the deleted protected function need, i can just re-do/copy the initial commits to bring the function back.... saves you doing it.... as long as you keep an eye on the commits so i dont break anything, particularly the changes you made today.

**Comment by creecros** [comment]
kind of because it's xmas and my wife won't leave me alone.

you can try, but I'm 99% sure it won't be that simple. 

yes I understand you want pre-installed colors to come with the plugin. as well as the ability to have users add. it can be done, but i think you will need to do it differently than before.

**Comment by aljawaid** [comment]
> kind of because it's xmas and my wife won't leave me alone.
> 
> you can try, but I'm 99% sure it won't be that simple.
> 
> yes I understand you want pre-installed colors to come with the plugin. as well as the ability to have users add. it can be done, but i think you will need to do it differently than before.

excellent... ok i cant afford to break it as it is so i will do only small cosmetic changes until you get the time.  I just need one or 2 colours back and then i will add to the list.  Importantly, the font color must be included.... if its the same syntax as the deleted protected function then i can figure it out....

**Comment by creecros** [comment]
Merged as best as I could, sorry if anything got lost. but now you have static preinstalled colors.

**Comment by aljawaid** [comment]
> Merged as best as I could, sorry if anything got lost. but now you have static preinstalled colors.

thats fine I really appreciate it... big thanks to you, i think many users will find this plugin useful now once v2 is released.  I will be renaming the plugin to ColorManager or something tonight just to make you aware so it will be a big change of file/folder names
